@startuml
'https://plantuml.com/state-diagram
[*] --> Начало_программы
Начало_программы --> Загрузка_данных: Начало программы
Загрузка_данных --> Проверка_сохраненных_данных: Данные загружены
Проверка_сохраненных_данных --> Вывод_меню: Сохраненные данные найдены
Проверка_сохраненных_данных --> Создание_пылесоса: Сохраненные данные не найдены
Создание_пылесоса --> Вывод_меню
Вывод_меню --> Запустить_пылесос: Выбран 1ый пункт меню
Вывод_меню --> Выбрать_насадку: Выбран 2ой пункт меню
Вывод_меню --> Посмотреть_засоренность_фильтра: Выбран 3ий пункт меню
Вывод_меню --> Посмотреть_засорен_ли_контейнер_для_пыли: Выбран 4ый пункт меню
Вывод_меню --> Посмотреть_какая_насадка_надета: Выбран 5ый пункт меню
Вывод_меню --> Изменить_текущую_мощность: Выбран 6ой пункт меню
Вывод_меню --> Посмотреть_установленную_мощность: Выбран 7ой пункт меню
Вывод_меню --> Выполнить_уборку_помещения: Выбран 8ой пункт меню
Вывод_меню --> Заменить_фильтр: Выбран 9ый пункт меню
Вывод_меню --> Очистить_контейнер_для_пыли: Выбран 10ый пункт меню
Вывод_меню --> Заменить_насадку: Выбран 11ый пункт меню
Вывод_меню --> Выполнить_техническое_обслуживание: Выбран 12ый пункт меню
Вывод_меню --> Выход: Выбран 13ый пункт меню

Запустить_пылесос --> Сохранение_состояния: Пылесос запущен
Выбрать_насадку --> Сохранение_состояния: Насадка выбрана
Изменить_текущую_мощность --> Сохранение_состояния: Мощность изменена
Выполнить_уборку_помещения --> Сохранение_состояния: Помещение убрано
Заменить_фильтр --> Сохранение_состояния: Фильтр заменен
Очистить_контейнер_для_пыли --> Сохранение_состояния: Контейнер для пыли очищен
Заменить_насадку --> Сохранение_состояния: Насадка заменена
Выполнить_техническое_обслуживание --> Сохранение_состояния: Техническое обслуживание выполнено

Посмотреть_засорен_ли_контейнер_для_пыли --> Вывод_меню
Посмотреть_засоренность_фильтра --> Вывод_меню
Посмотреть_какая_насадка_надета --> Вывод_меню
Посмотреть_установленную_мощность --> Вывод_меню
Сохранение_состояния --> Вывод_меню
Выход --> Завершение_программы

Завершение_программы --> [*]

state Запустить_пылесос {
    [*] --> Ввод_желаемой_мощности
    Ввод_желаемой_мощности --> [*]: Введена некорректная мощность
    Ввод_желаемой_мощности --> Запуск_пылесоса: Введена корректная мощность
    Запуск_пылесоса --> [*]
}

state Выбрать_насадку {
    [*] --> Ввод_названия_насадки
    Ввод_названия_насадки --> Одевание_насадки: Насадка выбрана корректно
    Ввод_названия_насадки --> [*]: Насадка выбрана некорректно
}

state Посмотреть_засоренность_фильтра {
    [*] --> Вывод_состояния_фильтра
    Вывод_состояния_фильтра --> [*]: Состояние фильтра выведено
}

state Посмотреть_засорен_ли_контейнер_для_пыли {
    [*] --> Вывод_состояния_контейнера
    Вывод_состояния_контейнера --> [*]: Контейнер засорен
    Вывод_состояния_контейнера --> [*]: Контейнер чист
}

state Посмотреть_какая_насадка_надета {
    [*] --> Вывод_надетой_насадки
    Вывод_надетой_насадки  --> [*]: Надетая насадка выведена
}

state Изменить_текущую_мощность {
    [*] --> Ввод_текущей_мощности
    Ввод_текущей_мощности --> [*]: Введена некорректная мощность
    Ввод_текущей_мощности --> Установка_текущей_мощности: Введена корректная мощность
    Установка_текущей_мощности --> [*]
}

state Посмотреть_установленную_мощность {
    [*] --> Вывод_текущей_мощности
    Вывод_текущей_мощности --> [*]: Текущая мощность выведена
}

state Выполнить_уборку_помещения {
    [*] --> Ввод_размеров_помещения
    Ввод_размеров_помещения --> [*]: Размеры введены некорректно
    Ввод_размеров_помещения --> Уборка_помещения: Размеры введены корректно
    Уборка_помещения --> Вывод_состояния_уборки: Помещение убирается
    Уборка_помещения --> Засорение_фильтра
    Уборка_помещения --> Засорение_контейнера_для_пыли
    Вывод_состояния_уборки --> [*]: Помещение убрано
}

state Заменить_фильтр {
    [*] --> Восстановление_здоровья_фильтра
    Восстановление_здоровья_фильтра --> [*]: Фильтр заменен
}

state Очистить_контейнер_для_пыли {
    [*] --> Изменение_состояния_контейнера_для_пыли
    Изменение_состояния_контейнера_для_пыли --> [*]: Контейнер для пыли очищен
}

state Заменить_насадку {
    [*] --> Ввод_насадки
    Ввод_насадки --> Изменение_состояния_насадок
    Изменение_состояния_насадок --> Выбрать_насадку
}

state Выполнить_техническое_обслуживание {
    [*] --> Изменение_состояния_двигателя
    Изменение_состояния_двигателя --> Заменить_фильтр
    Заменить_фильтр --> Очистить_контейнер_для_пыли
}
@enduml